name: scipy-2023-talk
channels:
  - conda-forge
dependencies:
  - python=3.10.8
  - pip
  - pip:
    - sunpy[all]
    - sunkit-image
    - ipykernel
    - s3fs
    - boto3
    - dask-gateway
    - cloudpickle==2.2.0
    - dask[diagnostics]==2022.11.1 
    - distributed==2022.11.1
    - lz4==4.0.2
    - msgpack==1.0.4
    - numpy==1.23.5
    - pandas==1.5.2
    - tornado==6.1
